import { parseEmbeddedMessage, type EmbeddedInitMessage } from '@ver-id/core';
import type { VeridEmbeddedError, VeridEmbeddedComponent } from './types.js';

/**
 * Optional iframe presentation attributes.
 *
 * @public
 */
export interface EmbeddedIframeOptions {
  className?: string;
  style?: Partial<CSSStyleDeclaration>;
  allow?: string;
  sandbox?: string;
  title?: string;
}

/**
 * Parameters for {@link mountEmbeddedVeridComponent}.
 *
 * @public
 */
export interface MountEmbeddedVeridComponentParams {
  /** Where to render the iframe: a container to create one in, or an existing iframe. */
  container: HTMLElement | HTMLIFrameElement;
  /** Ver.iD gateway URL. Its origin is the pinned trust anchor for postMessage. */
  gatewayUri: string;
  /** Flow uuid (OAuth client_id). */
  clientId: string;
  /** Scopes to request. */
  scope: string;
  /** PKCE state — generated by the backend, echoed back on the webhook. */
  state: string;
  /** PKCE code_challenge — generated by the backend (verifier stays server-side). */
  codeChallenge: string;
  /** Server-to-server webhook target the backend listens on. */
  webhookUri: string;
  /** Issuance only: the intent id created server-side. */
  intentId?: string;
  /** Optional iframe attributes. */
  iframe?: EmbeddedIframeOptions;
}

const DEFAULT_IFRAME_ALLOW = 'camera; microphone';
const DEFAULT_IFRAME_SANDBOX = 'allow-scripts allow-same-origin';
const DEFAULT_IFRAME_TITLE = 'Ver.iD embedded flow';

/** Mounts the Ver.iD iframe and re-dispatches inbound messages as typed `CustomEvent`s. */
export class VeridEmbeddedComponentImpl extends EventTarget implements VeridEmbeddedComponent {
  readonly iframe: HTMLIFrameElement;

  readonly #gatewayOrigin: string;
  readonly #initMessage: EmbeddedInitMessage;
  readonly #ownsIframe: boolean;
  readonly #onMessage = (event: MessageEvent): void => this.#handleMessage(event);
  readonly #onLoad = (): void => this.#postInit();
  #destroyed = false;

  constructor(params: MountEmbeddedVeridComponentParams) {
    super();

    this.#gatewayOrigin = new URL(params.gatewayUri).origin;
    this.#initMessage = {
      type: 'ronan:init',
      clientId: params.clientId,
      scope: params.scope,
      state: params.state,
      intentId: params.intentId ?? '',
      codeChallenge: params.codeChallenge,
      webhookUri: params.webhookUri,
    };

    if (params.container instanceof HTMLIFrameElement) {
      this.iframe = params.container;
      this.#ownsIframe = false;
    } else {
      this.iframe = document.createElement('iframe');
      params.container.appendChild(this.iframe);
      this.#ownsIframe = true;
    }

    this.#applyIframeOptions(params.iframe);
    this.iframe.addEventListener('load', this.#onLoad);
    window.addEventListener('message', this.#onMessage);
    this.iframe.src = params.gatewayUri;
  }

  #applyIframeOptions(options: EmbeddedIframeOptions | undefined): void {
    this.iframe.allow = options?.allow ?? DEFAULT_IFRAME_ALLOW;
    this.iframe.setAttribute('sandbox', options?.sandbox ?? DEFAULT_IFRAME_SANDBOX);
    this.iframe.title = options?.title ?? DEFAULT_IFRAME_TITLE;
    if (options?.className !== undefined) {
      this.iframe.className = options.className;
    }
    if (options?.style) {
      Object.assign(this.iframe.style, options.style);
    }
  }

  #postInit(): void {
    const target = this.iframe.contentWindow;
    if (target === null) {
      return;
    }
    target.postMessage(this.#initMessage, this.#gatewayOrigin);
  }

  #handleMessage(event: MessageEvent): void {
    if (event.origin !== this.#gatewayOrigin) {
      return;
    }
    if (event.source !== this.iframe.contentWindow) {
      return;
    }

    const parsed = parseEmbeddedMessage(event.data);
    if (!parsed.ok) {
      this.#dispatchError({ error: 'invalid_message', error_description: parsed.reason });
      return;
    }

    switch (parsed.message.type) {
      case 'ronan:ready':
        this.dispatchEvent(new CustomEvent('ready'));
        return;
      case 'ronan:complete':
        this.dispatchEvent(new CustomEvent('complete'));
        return;
      case 'ronan:error':
        this.#dispatchError(
          parsed.message.error_description === undefined
            ? { error: parsed.message.error }
            : { error: parsed.message.error, error_description: parsed.message.error_description },
        );
        return;
      case 'ronan:cancel':
        this.dispatchEvent(new CustomEvent('cancel'));
        return;
    }
  }

  #dispatchError(detail: VeridEmbeddedError): void {
    this.dispatchEvent(new CustomEvent('error', { detail }));
  }

  destroy(): void {
    if (this.#destroyed) {
      return;
    }
    this.#destroyed = true;
    window.removeEventListener('message', this.#onMessage);
    this.iframe.removeEventListener('load', this.#onLoad);
    if (this.#ownsIframe) {
      this.iframe.remove();
    }
  }
}
